name: pokeapi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
